In [27]:
from operator import index

import pandas as pd
import os

In [28]:
dataframes = {}

pf_df = pd.read_json('./staging_data/raw/payload_flights.json')
payload_df = pd.DataFrame(pf_df['results'].tolist())

sf_df = pd.read_json('./staging_data/raw/spacecraft_flights.json')
spacecraft_df = pd.DataFrame(sf_df['results'].tolist())

a = pd.read_json('./staging_data/raw/launches.json')
lau_df = pd.DataFrame(a['results'].tolist())

b = pd.read_json('./staging_data/raw/landings.json')
lan_df = pd.DataFrame(b['results'].tolist())

print("payload cols", payload_df.columns)
print("spacecraft cols", spacecraft_df.columns)

payload cols Index(['response_mode', 'id', 'url', 'destination', 'amount', 'payload',
       'launch', 'landing'],
      dtype='object')
spacecraft cols Index(['id', 'url', 'destination', 'mission_end', 'spacecraft', 'launch',
       'landing', 'duration', 'turn_around_time', 'response_mode'],
      dtype='object')

In [29]:
def check_types(df:pd.DataFrame):
    for col in df.columns:
        if df[col].apply(lambda x: isinstance(x, dict)).any():
            print(col)

print("========== Payload ==========")
check_types(payload_df)
print("========== Spacecraft ==========")
check_types(spacecraft_df)

========== Payload ==========
payload
launch
landing
========== Spacecraft ==========
spacecraft
launch
landing

In [30]:
pd.DataFrame(spacecraft_df['spacecraft'].tolist()).head()

,response_mode,id,url,name,serial_number,is_placeholder,image,in_space,time_in_space,time_docked,flights_count,mission_ends_count,status,description,spacecraft_config,fastest_turnaround
0,normal,541,https://lldev.thespacedevs.com/2.3.0/spacecraf...,Orion 004,004,False,"{'id': 1919, 'name': 'Orion approaching the Mo...",False,P0D,P0D,0,0,"{'id': 5, 'name': 'Under construction'}",Orion spacecraft used for Artemis 3.,"{'response_mode': 'normal', 'id': 4, 'url': 'h...",None
1,normal,290,https://lldev.thespacedevs.com/2.3.0/spacecraf...,Starliner 2,2,False,"{'id': 1020, 'name': 'Boeing Starliner in orbi...",False,P5DT23H54M13S,P4DT18H8M,1,1,"{'id': 1, 'name': 'Active'}",The second CST-100 Starliner capsule to fly.,"{'response_mode': 'normal', 'id': 9, 'url': 'h...",None
2,normal,540,https://lldev.thespacedevs.com/2.3.0/spacecraf...,Orion Integrity,003,False,"{'id': 1919, 'name': 'Orion approaching the Mo...",False,P9DT1H32M15S,P0D,1,1,"{'id': 1, 'name': 'Active'}",Orion spacecraft used for Artemis 2.,"{'response_mode': 'normal', 'id': 4, 'url': 'h...",None
3,normal,447,https://lldev.thespacedevs.com/2.3.0/spacecraf...,Dream Chaser Tenacity,None,False,"{'id': 1913, 'name': 'Dream Chaser Eagle on th...",False,P0D,P0D,0,0,"{'id': 1, 'name': 'Active'}",First operational Dream Chaser.,"{'response_mode': 'normal', 'id': 24, 'url': '...",None
4,normal,548,https://lldev.thespacedevs.com/2.3.0/spacecraf...,Gaganyaan G2,None,False,"{'id': 1914, 'name': '[AUTO] Gaganyaan - image...",False,P0D,P0D,0,0,"{'id': 4, 'name': 'Single Use'}",Second operational Gaganyaan capsule.,"{'response_mode': 'normal', 'id': 29, 'url': '...",None

In [31]:
######### move spacecraft_id to launch
spacecraft_launches = pd.DataFrame(spacecraft_df['launch'].tolist())
spacecraft_launches['spacecraft_id'] = pd.DataFrame(spacecraft_df['spacecraft'].tolist())['id']

spacecraft_landings = pd.DataFrame(spacecraft_df['landing'].dropna().tolist())
spacecraft_landings['spacecraft_id'] = pd.DataFrame(spacecraft_df['landing'].tolist())['id']

launch_df = pd.concat(
    [
        pd.DataFrame(payload_df['launch'].tolist()),
        spacecraft_launches,
        lau_df
    ],
    ignore_index=True
)

landing_df = pd.concat(
    [
        pd.DataFrame(payload_df['landing'].dropna().tolist()),
        spacecraft_landings,
        lan_df
    ],
    ignore_index=True
)

print("============ Launch",
        launch_df.columns.tolist(),
        launch_df.shape, sep="\n")
print("---")
check_types(launch_df)
print("============ Landing",
      landing_df.columns.tolist(),
        landing_df.shape, sep="\n")
print("---")
check_types(landing_df)

============ Launch
['id', 'url', 'name', 'response_mode', 'slug', 'launch_designator', 'status', 'last_updated', 'net', 'net_precision', 'window_end', 'window_start', 'image', 'infographic', 'probability', 'weather_concerns', 'failreason', 'hashtag', 'launch_service_provider', 'rocket', 'mission', 'pad', 'webcast_live', 'program', 'orbital_launch_attempt_count', 'location_launch_attempt_count', 'pad_launch_attempt_count', 'agency_launch_attempt_count', 'orbital_launch_attempt_count_year', 'location_launch_attempt_count_year', 'pad_launch_attempt_count_year', 'agency_launch_attempt_count_year', 'spacecraft_id']
(150, 33)
---
status
net_precision
image
launch_service_provider
rocket
mission
pad
============ Landing
['id', 'url', 'attempt', 'success', 'description', 'downrange_distance', 'landing_location', 'type', 'spacecraft_id', 'response_mode', 'firststage', 'spacecraftflight', 'payloadflight']
(139, 13)
---
landing_location
type
firststage
spacecraftflight

C:\Users\retti\AppData\Local\Temp\ipykernel_21380\2787992788.py:17: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  landing_df = pd.concat(

In [32]:
rocket_df = pd.DataFrame(
    launch_df['rocket']
        .tolist()
)


rocket_df = pd.concat(
    [
        rocket_df.drop(columns=['configuration']),
        pd.json_normalize(rocket_df['configuration'])
    ],
    axis=1
)

rocket_df.to_csv('./staging_data/splitted/rockets.csv')
rocket_df = rocket_df.loc[:, ~rocket_df.columns.duplicated()]
rocket_df.to_json('./staging_data/splitted/rockets.json', orient='records', indent=4)

rocket_df.head()

,id,response_mode,url,name,families,full_name,variant
0,9063,list,https://lldev.thespacedevs.com/2.3.0/launcher_...,Falcon 9,"[{'response_mode': 'list', 'id': 1, 'name': 'F...",Falcon 9 Block 5,Block 5
1,7783,list,https://lldev.thespacedevs.com/2.3.0/launcher_...,New Glenn,"[{'response_mode': 'list', 'id': 214, 'name': ...",New Glenn,
2,7783,list,https://lldev.thespacedevs.com/2.3.0/launcher_...,New Glenn,"[{'response_mode': 'list', 'id': 214, 'name': ...",New Glenn,
3,2489,list,https://lldev.thespacedevs.com/2.3.0/launcher_...,Falcon Heavy,"[{'response_mode': 'list', 'id': 1, 'name': 'F...",Falcon Heavy,Heavy
4,8811,list,https://lldev.thespacedevs.com/2.3.0/launcher_...,Pegasus XL,"[{'response_mode': 'list', 'id': 117, 'name': ...",Pegasus XL,

In [33]:
provider_df = pd.DataFrame(
    launch_df['launch_service_provider']
        .tolist()
)

provider_df.to_csv('./staging_data/splitted/providers.csv')
provider_df.to_json('./staging_data/splitted/providers.json', orient='records', indent=4)

# provider_df.head()

mission_df = pd.DataFrame(
    launch_df['mission']
        .tolist()
).drop(['agencies','info_urls','vid_urls','image'],axis=1)

# mission_df.head()
mission_df.to_csv('./staging_data/splitted/missions.csv')
mission_df.to_json('./staging_data/splitted/missions.json', orient='records', indent=4)


pad_df = pd.DataFrame(
    launch_df['pad']
        .tolist()
).drop(['agencies'],axis=1)

pad_df.to_csv('./staging_data/splitted/pads.csv')
pad_df.to_json('./staging_data/splitted/pads.json', orient='records', indent=4)


launch_df.to_csv('./staging_data/splitted/launches.csv')
launch_df.to_json('./staging_data/splitted/launches.json', orient='records', indent=4)

In [38]:
p_df = pd.DataFrame(
    payload_df['payload']
        .tolist()
).drop(['image'],axis=1)
check_types(p_df)

p_df.to_csv('./staging_data/splitted/payloads.csv')

agencies_df = pd.concat(
    [
        pd.DataFrame(p_df['manufacturer'].dropna().tolist()),
        pd.DataFrame(p_df['operator'].dropna().tolist())
    ],
    ignore_index=True
)

agencies_df.to_csv('./staging_data/splitted/agencies.csv')
agencies_df.to_json('./staging_data/splitted/agencies.json', orient='records', indent=4)


programs_df = pd.DataFrame(
    payload_df['payload']
        .tolist()
).dropna()

programs_df.head()

programs_df.to_csv('./staging_data/splitted/programs.csv')
programs_df.to_json('./staging_data/splitted/programs.json', orient='records', indent=4)

type
manufacturer
operator

In [35]:
s_df = pd.DataFrame(
    spacecraft_df['spacecraft'].tolist()
)

# s_df.head()

s_df.to_csv('./staging_data/splitted/spacecrafts.csv')
s_df.to_json('./staging_data/splitted/spacecrafts.json', orient='records', indent=4)

In [36]:
landing_df.to_csv('./staging_data/splitted/landings.csv')
landing_df.to_json('./staging_data/splitted/landings.json', orient='records', indent=4)

In [81]:
# 


cond = landing_df['spacecraftflight'].notna()
a = pd.DataFrame(landing_df[cond]['spacecraftflight'].to_list())
launch = pd.DataFrame(a['launch'].to_list())
b = pd.DataFrame(launch['mission'].to_list())
b.head()
orbit_df = pd.concat([
    pd.DataFrame(mission_df['orbit'].to_list()),
    pd.DataFrame(b['orbit'].to_list()),
], ignore_index=True)

orbit_df.head()
orbit_df.to_csv('./staging_data/splitted/orbits.csv')
orbit_df.to_json('./staging_data/splitted/orbits.json', orient='records', indent=4)